FROM amazonlinux:2


#################################################
# Install tools & nvm,node
################################################# curl bash
RUN yum -y update && \
    yum install -y git less tar gzip wget gcc make python3 unzip jq rsync which

ARG NVM_VERSION
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh | bash

ARG NODE_VERSION
RUN /bin/bash -c "source /root/.nvm/nvm.sh; nvm install ${NODE_VERSION}" 
RUN { \
  echo 'export NVM_DIR=~/.nvm'; \
  echo '. ~/.nvm/nvm.sh'; \
  } > /root/.bashrc
CMD /bin/bash -c "source ~/.nvm/nvm.sh; nvm use ${NODE_VERSION}"


#################################################
# Install docker,docker-compose
#################################################
RUN amazon-linux-extras install docker -y
ARG COMPOSE_VERSION
RUN curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose \
    && ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose


#################################################
# Install AWS CLI v2
#################################################
# RUN curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip \
#     && unzip /tmp/awscliv2.zip -d /tmp \
#     && /tmp/aws/install \
#     && rm -f /tmp/awscliv2.zip \
#     && rm -rf /tmp/aws
